version: '3'

services:
  postgres:
    image: postgres:16
    container_name: ${DB_HOST}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5454:5432"
    networks:
      - my_network
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: unless-stopped  # Reinicio del servicio a menos que se detenga manualmente

  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app

    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - postgres
    networks:
      - my_network
    volumes:
      - ./gestion_filas:/app/gestion_filas
      - ./Pipfile:/app/Pipfile
      - ./Pipfile.lock:/app/Pipfile.lock
    restart: unless-stopped  # Reinicio del servicio a menos que se detenga manualmente

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8008:80"
    depends_on:
      - postgres
    networks:
      - my_network
    restart: unless-stopped  # Reinicio del servicio a menos que se detenga manualmente

networks:
  my_network:
