# Generated by Django 4.2.7 on 2023-11-27 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listaEspera', '0003_rename_rut_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='atendido',
        ),
        migrations.CreateModel(
            name='TomaEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_espera', models.IntegerField()),
                ('fecha_toma', models.DateTimeField(auto_now_add=True)),
                ('atendido', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listaEspera.paciente')),
            ],
        ),
    ]
