# Generated by Django 4.2.7 on 2023-11-28 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listaEspera', '0004_remove_paciente_atendido_tomaespera'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='rut_number',
            new_name='numero_telefono',
        ),
    ]
