# Generated by Django 4.2.7 on 2023-11-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaEspera', '0006_alter_tomaespera_numero_espera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tomaespera',
            name='numero_espera',
            field=models.IntegerField(),
        ),
    ]
