# Generated by Django 4.2.7 on 2023-12-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaEspera', '0011_alter_paciente_numero_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='numero_telefono',
        ),
        migrations.AddField(
            model_name='paciente',
            name='num_identificador',
            field=models.CharField(default='Sin Teléfono', max_length=12),
        ),
    ]
