# Generated by Django 4.2.7 on 2023-12-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listaEspera', '0012_remove_paciente_numero_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='num_identificador',
            field=models.CharField(default='Sin Rut', max_length=12),
        ),
    ]
